
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@mail.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "0d2676ae-eb95-481f-9046-3a4081859dc8"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "f04aae7f-81e5-4be1-b404-56fc334e9a52",
  "account_id_to": "0d2676ae-eb95-481f-9046-3a4081859dc8",
  "amount": 1
}